config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#show"
  resources :users, only:[:edit,:update, :show] do
    resources :favorites, only:[:index]
  end 
  resources :rooms, only: [:new, :create, :destroy] ,shallow: true do
    resources :messages, only: [:index, :create, :destroy]
    resources :tasks, except: [:new],shallow: true do
      resources :favorites,only:[:create,:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users  
  has_many :messages, dependent: :destroy
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_many :favorites, dependent: :destroy 

  validates :task_name, presence: true
  validates :status,    presence: true
  validates :limit,     presence: true
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :tasks
  has_many :favorites, dependent: :destroy     

  validates :nickname, presence: true, uniqueness: true,length: { maximum: 15 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user! 

  def create
      @task = Task.find(params[:task_id])
      @favorite = Favorite.create(user_id: current_user.id, task_id: @task.id)
      redirect_to room_tasks_path(@task.room_id)
  end

  def destroy
    @task = Task.find(params[:id])
    @favorite = Favorite.find_by(user_id: current_user.id, task_id: @task.id)
    @favorite.destroy
    redirect_to root_path
  end
  

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user).order(id: "DESC")
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

    def destroy
      @message = Message.find(params[:id])
      @message.destroy
      redirect_to room_messages_path(@message.room_id)
     end

     

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.new
    @room = Room.find(params[:room_id])
    @tasks = @room.tasks.includes(:user).order(limit: "ASC")
  end

  def create
    @room = Room.find(params[:room_id])
    @task = @room.tasks.new(task_params)
    if @task.save
      redirect_to room_tasks_path(@room)
    else
      @tasks = @room.tasks.includes(:user)
      render :index
    end
  end

  def edit
    @task = Task.find(params[:id])
    @room = @task.room_id
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to room_tasks_path(@task.room_id)
    else
      render :edit
    end
  end

  def destroy
   @task = Task.find(params[:id])
   @task.destroy
   redirect_to room_tasks_path(@task.room_id)
  end

  def show
    @task = Task.find(params[:id])
    @room = @task.room_id
    @room_info = Room.find(@room)
  end

  
  private

  def task_params
    params.require(:task).permit(:status,:limit,:task_name,:details).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end


  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    favorites = Favorite.where(user_id: current_user.id).pluck(:task_id) 
    @favorite_list = Task.find(favorites)
  end
  
  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task32150</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/messages/_side_bar.html.erb
 <%# <div class="rooms"> %>
    <% current_user.rooms.each do |room| %>
    <div class="room">
        <%= link_to room.name, room_tasks_path(room),class:"room-name" %>
    </div>
  <% end %>
  <%# </div> %>

app/views/messages/index.html.erb
 <%= render "shared/header" %>


<div class="main">
   <div class="side-bar">
  <div class="side-bar-title">
  <h4 class="side-bar-text">ROOM</h4>
  </div>
  <div class="side-bar-main">
    <%= render "messages/side_bar" %>
  </div>
  </div>


  <div class="main-task-chat">
  <div class="task-chat">


<div class="chat-header">
   <div class="left-header">
   <div class="task-chat-room-name">
      <%= @room.name %>
      </div>
    </div>
    <%= link_to "ROOM DELETE", room_path(@room), method: :delete,class:"room-delete-btn" %>
  </div>

   <div class="task-chat-selector">
   <div class="task-selector">
   <%= link_to "task", room_tasks_path(@room),class:"selector" %>
   </div>
   <div class="chat-selector">
   <%= link_to "chat", room_messages_path(@room),class:"selector" %>
   </div>
   </div>

   
  <div class="messages-position">
  <%= render "shared/main_chat" %>
  </div>
  

  <div class="form-position">
  <%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>
</div>



  </div>
  </div>

</div>

app/views/rooms/index.html.erb
<div class="page">
<%= render "shared/header" %>


<div class="main">
  <div class="side-bar">
  <div class="side-bar-title">
  <h4 class="side-bar-text">ROOM</h4>
  </div>

  <div class="side-bar-main">
    <%= render "messages/side_bar" %>
    
  </div>
  </div>


  <div class="main-task-chat">
  <div class="task-chat">
  <div class="main-title">
  <h2> YOUR TASK LIST</h2>
  <div class="create-btn" id="task-create-btn">
    new task
    </div>
  </div>
  <div class="task-chat-selector">
   <div class="task-selector">
   <%= link_to "task", "#",class:"selector" %>
   </div>
   <div class="chat-selector">
   <%= link_to "chat", "#",class:"selector" %>
   </div>
   </div>


  <div class="my-tasks">
  
    <div class="task-bar">
         <div class="task-bar-info">
          <div class="tasks-info">
          <p class="task-status">status</p>
          </div>
          <div class="tasks-info">
          <p class="task-limit">limit</p>
          </div>          
          <div class="tasks-info">
          <p class="task-title">title</p>
          </div>
          <div class="tasks-info">
          <p class="task-manage">manage</p>
          </div>
        </div>
  </div>
   

    <ul class="tasks">
     <li class="task">
     <div class="task-info">
          <div class="tasks-infomation green">
          task-status
          </div>
          <div class="tasks-infomation limit">
          task-limit
          </div>          
          <div class="tasks-infomation title">
          task
          </div>
          <div class="tasks-infomation manege">
              <%= link_to '編集', "#", method: :get, class:"edit-btn" %>
            <%= link_to "削除","#", method: :delete,  class:"destroy-btn"%>
          </div>
        </div>
     </li>

     <ul class="app-task">
     このアプリでできること
     <li>ヘッダーの new roomボタンからルーム作成してユーザーで共有！</li>
     <li>共有したいタスクを new taskボタンから投稿！</li>
     <li>編集・消去ボタンを利用してタスク状況を管理！</li>
     <li>chatボタンを押すとルーム内でのchatが可能！</li>
     家族や仲間でタスクを共有していこう！
     </ul>

  
    
    
   
  </div> 
  </div>
  </div>
</div>
</div>

app/views/rooms/new.html.erb
<div class="user-edit" >
<%= render "shared/second_header" %>

</div>
  <div id="edit-task">
  <div class="modal">
    <h1>新規チャットルーム</h1>
      <%= link_to "TOPページに戻る", "/", class: 'btn'%>
   <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form-field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form-field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form'>
      <% 6.times do%>
      <select name="room[user_ids][]">
        <option value="">チャットするユーザーを選択してください</option>
         <% User.where.not(id: current_user.id).each do |user| %>
        <option value=<%= user.id %>><%= user.nickname %></option>
        <% end %>
      </select>
      <%end%>
      <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>

      
    </div>
    <div class='chat-room-form-field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

</div>
</div>
<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<div class="footer">
 <div class="footer-logo">TaskIsEasy</div>
 <div class="footer-list">
 </div>
</div>

app/views/shared/_header.html.erb
<div class="header">

 <div class="header-logo">
    <h2>
    <%= link_to "TaskToManage", "/", class:"header-title" %></li>
    </h2>
</div>

  <div class="header-user-menu">
    <ul class="menus">
    <li class="menu"><%= link_to "new room", new_room_path, class: "link" %></li>
    <li class="menu"><%= link_to "ユーザー編集", edit_user_path(current_user),class:"link" %></li>
    <li class="menu"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "link" %></li>
    </ul>
  </div>
  
</div>

app/views/shared/_main_chat.html.erb
<div class="messages">
  <%= render partial: 'shared/message', collection: @messages %>
</div>

app/views/shared/_message.html.erb
<div class="message-info">
    <div class="message-upp">
    <div class="message-user">
      <%= message.user.nickname %>
    </div>
    <div class="message-date">
       <%= l message.created_at %>
    </div>
    </div>

    <div class="message-down">
    <div class="message-top">
    <div class="message-content">
      <%= message.content %>
       </div>
       <div class="message-delete">
      <%= link_to "削除", message_path(message), method: :delete,  class:"message-destroy-btn"%>
      </div>
      </div>
    <div class="message-image">
      <%= image_tag message.image.variant(resize: '200x200'), class: 'message-image' if message.image.attached? %>
    </div>
    </div>

   
  </div>

app/views/shared/_second_header.html.erb
<div class="header">

 <div class="header-logo">
    <h2>
    <%= link_to "TaskToManage", "/", class:"header-title" %></li>
    </h2>
</div>
</div>

app/views/tasks/edit.html.erb
<%= render "shared/second_header" %>

<div id="edit-task">
  <div class="modal">
    <div class="top-task-selector">
     <%= link_to "TOPページに戻る", "/", class: 'btn' ,id:"top-btn"%>
      <%= link_to "taskページに戻る", room_tasks_path(@room),class:"selector",id:"task-btn" %>
    </div>
<%= form_with model: @task, class: 'task-form', local: true do |f| %>
  <div class="form-input">
    <div class="task-form-list">
    <%= f.label :task_name %><br>
    <%= f.text_field :task_name, class: 'form-task-name', placeholder: 'type a task name' %>
    </div>
    <div class="task-form-list">
    <%= f.label :state %><br>
    <%= f.select(:status, [['todo', 'todo'], ['doing', 'doing'], ['done', 'done']]) %>
    </div>
    <div class="task-form-list">
    <%= f.label :limit_time %><br>
   <%=f.date_field  :limit, class:'form-limit'%>
   </div>
   <div class="task-form-list">
    <%= f.label :task_details %><br>
   <%=f.text_area :details, size:"50*50",class:'form-limit'%>
   </div>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>
</div>
</div>
<%= render "shared/footer" %>

app/views/tasks/index.html.erb
<div class="page">
<%= render "shared/header" %>


<div class="main">
  <div class="side-bar">
  <div class="side-bar-title">
  <h4 class="side-bar-text">ROOM</h4>
  </div>

  <div class="side-bar-main">
    <%= render "messages/side_bar" %>
  </div>
  </div>


  <div class="main-task-chat">

   <div class="task-chat">
    <%= link_to "ROOM DELETE", room_path(@room), method: :delete,class:"room-delete-btn" %>

    <div class="main-title">
  <h2> <%=@room.name%><br> TASK LIST</h2>
    <div class="create-btn" id="task-create-btn">
    new task
    </div>
  </div>
<div class="task-chat-selector">
   <div class="task-selector">
   <%= link_to "task", room_tasks_path(@room),class:"selector" %>
   </div>
   <div class="chat-selector">
   <%= link_to "chat", room_messages_path(@room),class:"selector" %>
   </div>
   </div>
   
  <div id="new-task-create" >
  <div class="modal">
  <div class="close-btn">閉じる</div>
<%= form_with model: [@room, @task], class: 'task-form', local: true do |f| %>
  <div class="form-input">
    <div class="task-form-list">
    <%= f.label :task_name %><br>
    <%= f.text_field :task_name, class: 'form-task-name', placeholder: 'type a task name' %>
    
    </div>
    <div class="task-form-list">
    
    <%= f.label :state %><br>
    <%= f.select(:status, [['todo', 'todo'], ['doing', 'doing'], ['done', 'done']]) %>
    </div>
    <div class="task-form-list">
    <%= f.label :limit_time %><br>
   <%=f.date_field  :limit, class:'form-limit'%>
   </div>
   <div class="task-form-list">
    <%= f.label :task_details %><br>
   <%=f.text_area :details, size:"50*50",class:'form-limit'%>
   </div>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>
</div>
</div>


  <%# <div class="my-tasks"> %>
  <div class="task-bar">
         <div class="task-bar-info">
          <div class="tasks-info">
          <p class="task-status">status</p>
          </div>
          <div class="tasks-info">
          <p class="task-limit">limit</p>
          </div>          
          <div class="tasks-info">
          <p class="task-title">title</p>
          </div>
          <div class="tasks-info">
          <p class="task-manage">manage</p>
          </div>
        </div>
  </div>


 <ul class="tasks">
      <% @tasks.each do |task| %>
     <li class="task">
     <%if task.status=="todo"%>
      <div class="task-info">
          <div class="task-info-status red">
          <%= task.status%>
          </div>
    <%elsif task.status=="doing"%>
     <div class="task-info">
          <div class="task-info-status green">
          <%= task.status%>
          </div>
    <%else %>
     <div class="task-info">
          <div class="task-info-status blue">
          <%= task.status%>
          </div>
    <%end%>
          <div class="limit">
          <%= task.limit%>
          </div>          
          <div class="title">
          <%= task.task_name%>
          </div>
          <div class="manage">
          <ul>
          <li><%= link_to '詳細', task_path(task), method: :get, class:"edit-btn" %></li>
          <li><%= link_to '編集', edit_task_path(task), method: :get, class:"edit-btn" %></li>
          <li> <%= link_to "削除", task_path(task), method: :delete,  class:"destroy-btn"%></li>
          <li><% if !Favorite.exists?(user: current_user, task_id: task.id)   %>
                <%= link_to "mytask",task_favorites_path(task), method: :post ,class:"favorite-btn"   %>
              <% end %></li>
              </ul>
          </div>
        </div>
     </li>
<%end%>
</ul>
    <div>

    </div>
  </div> 
  </div>
  </div>
</div>
</div>

app/views/tasks/show.html.erb
<div class="page">
<%= render "shared/header" %>


<div class="main">
  <div class="side-bar">
  <div class="side-bar-title">
  <h4 class="side-bar-text">ROOM</h4>
  </div>

  <div class="side-bar-main">
    <%= render "messages/side_bar" %>
  </div>
  </div>




   <div class="main-task-chat">
  <div class="task-chat">
  <div class="main-title">
  <h2> TASK DETAILS </h2>
  <div class="detail-menus">
  <%= link_to '編集', edit_task_path(@task), method: :get, class:"detail-edit-btn btn" %>
  <%= link_to "taskページに戻る", room_tasks_path(@room),class:"selector",class:"detail-task-btn btn" %>
  <%= link_to "削除", task_path(@task), method: :delete,  class:"detail-destroy-btn btn"%>
  <% if !Favorite.exists?(user: current_user, task_id: @task.id)   %>
      <%= link_to "mytask",task_favorites_path(@task), method: :post ,class:"detail-favorite-btn btn"   %>
   <% end %>
  </div>
  </div>

 <div class="task-details">
<table class="task-table">
<tbody>
<tr>
<td class="left">task name</td>
<td class="right"><%=@task.task_name%></td>
</tr>
</tbody>
<tbody>
<tr>
<td class="left">room name</td>
<td class="right"><%=@room_info.name%></td>
</tr>
</tbody>
<tbody>
<tr>
<td class="left">status</td>
<td class="right"><%=@task.status%></td>
</tr>
</tbody>
<tbody>
<tr>
<td class="left">limit</td>
<td class="right"><%=@task.limit%></td>
</tr>
</tbody>
<tbody>
<tr>
<td class="left-detail">details</td>
<td class="right-detail"><%=@task.details%></td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
 

app/views/users/edit.html.erb
 <div class="user-edit" >
<%= render "shared/second_header" %>
  <div id="edit-task">
  <div class="modal">
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "TOPページに戻る", "/", class: 'btn'%>
   <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
</div>

</div>
</div>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<div class="page">
<%= render "shared/header" %>


<div class="main">
  <div class="side-bar">
  <div class="side-bar-title">
  <h4 class="side-bar-text">ROOM</h4>
  </div>

  <div class="side-bar-main">
    <%= render "messages/side_bar" %>
  </div>
  </div>


  <div class="main-task-chat">
  <div class="task-chat">
  <div class="main-title">
  <h2> YOUR TASK LIST</h2>
 
  </div>

  <%# <div class="my-tasks"> %>
    <div class="task-bar">
         <div class="task-bar-info">
          <div class="tasks-info">
          <p class="task-status">status</p>
          </div>
          <div class="tasks-info">
          <p class="task-limit">limit</p>
          </div>          
          <div class="tasks-info">
          <p class="task-title">title</p>
          </div>
          <div class="tasks-info">
          <p class="task-manage">manage</p>
          </div>
        </div>
  </div>

<ul class="tasks">
      <% if @favorite_list.present? %>
         <% @favorite_list.each do |task| %>
     <li class="task">
     <%if task.status=="todo"%>
      <div class="task-info">
          <div class="task-info-status red">
          <%= task.status%>
          </div>
    <%elsif task.status=="doing"%>
     <div class="task-info">
          <div class="task-info-status green">
          <%= task.status%>
          </div>
    <%else %>
     <div class="task-info">
          <div class="task-info-status blue">
          <%= task.status%>
          </div>
    <%end%>
          <div class="limit">
          <%= task.limit%>
          </div>          
          <div class="title">
          <%= task.task_name%>
          </div>
          <div class="manage">
          <ul>
          <li> <%= link_to '編集', edit_task_path(task), method: :get, class:"edit-btn" %></li>
           <li> <%= link_to "削除", task_path(task), method: :delete,  class:"destroy-btn"%></li>
          <li> <% if Favorite.exists?(user: current_user, task_id: task.id)   %>
                <%= link_to favorite_path(task), method: :delete, class: "favorite-delete" do %>
           <div class="i far fa-thumbs-up remove">
                    <span>roomに戻す</span>
                   </div></li>
                <% end %>
              <% end %>
          </div>
        </div>
     </li>
     <%end%>
<%end%>
</ul>
    

    </div>
  </div> 
  </div>
  </div>
</div>
</div>